	<div class="sub_container">
		<div class="content">
			<div class="register_status_bar2">
				<ul>
					<li>STEP 01 >></li>
					<li>STEP 02 >></li>
					<li><span class="on">STEP 03 >></span></li>
					<li>STEP 04 >></li>
					<li>STEP 05</li>
				</ul>
			</div>
			<div class="register_step3_msg_bar">
				<p> We confirm your success. Please fill out the form below.</p>
			</div>
			<h3>Contact Information</h3>
			<form method="post" name="frmRegisterStep3" id="frmRegisterStep3" action="/auth/signUp/step3_process">
			<div class="layerBox2 register_form_box">

				<ul class="inputListRegisterStep3">
					<li><p class="font_set_orange">* required fields</p></li>
					<li><label>User Email :</label> <?php echo $tempUserEmail?></li>
                    <li><label>Full Name<span class="font_set_orange">*</span> :</label><input type="text" name="userName" id="userName" /><p class="error_msg"></p></li>
					<li><label>Company Name<span class="font_set_orange"></span> :</label><input type="text" name="userCompany" id="userCompany" /><p class="error_msg"></p></li>
					<li><label>Country<span class="font_set_orange">*</span> :</label>
						<select name="userCountry">
						    <option>Afghanistan</option>
						    <option>Albania</option>
						    <option>Algeria</option>
						    <option>American Samoa</option>
						    <option>Andorra</option>
						    <option>Angola</option>
						    <option>Anguilla</option>
						    <option>Antarctica</option>
						    <option>Antigua And Barbuda</option>
						    <option>Argentina</option>
						    <option>Armenia</option>
						    <option>Aruba</option>
						    <option>Australia</option>
						    <option>Austria</option>
						    <option>Azerbaijan</option>
						    <option>Bahamas</option>
						    <option>Bahrain</option>
						    <option>Bangladesh</option>
						    <option>Barbados</option>
						    <option>Belarus</option>
						    <option>Belgium</option>
						    <option>Belize</option>
						    <option>Benin</option>
						    <option>Bermuda</option>
						    <option>Bhutan</option>
						    <option>Bolivia</option>
						    <option>Bosnia and Herzegovina</option>
						    <option>Botswana</option>
						    <option>Bouvet Island</option>
						    <option>Brazil</option>
						    <option>British Indian Ocean Territory</option>
						    <option>Brunei Darussalam</option>
						    <option>Bulgaria</option>
						    <option>Burkina Faso</option>
						    <option>Burundi</option>
						    <option>Cambodia</option>
						    <option>Cameroon</option>
						    <option>Canada</option>
						    <option>Cape Verde</option>
						    <option>Cayman Islands</option>
						    <option>Central African Republic</option>
						    <option>Chad</option>
						    <option>Chile</option>
						    <option>China</option>
						    <option>Christmas Island</option>
						    <option>Cocos (Keeling) Islands</option>
						    <option>Colombia</option>
						    <option>Comoros</option>
						    <option>Congo</option>
						    <option>Congo, the Democratic Republic of the</option>
						    <option>Cook Islands</option>
						    <option>Costa Rica</option>
						    <option>Cote d'Ivoire</option>
						    <option>Croatia</option>
						    <option>Cyprus</option>
						    <option>Czech Republic</option>
						    <option>Denmark</option>
						    <option>Djibouti</option>
						    <option>Dominica</option>
						    <option>Dominican Republic</option>
						    <option>East Timor</option>
						    <option>Ecuador</option>
						    <option>Egypt</option>
						    <option>El Salvador</option>
						    <option>England</option>
						    <option>Equatorial Guinea</option>
						    <option>Eritrea</option>
						    <option>Espana</option>
						    <option>Estonia</option>
						    <option>Ethiopia</option>
						    <option>Falkland Islands</option>
						    <option>Faroe Islands</option>
						    <option>Fiji</option>
						    <option>Finland</option>
						    <option>France</option>
						    <option>French Guiana</option>
						    <option>French Polynesia</option>
						    <option>French Southern Territories</option>
						    <option>Gabon</option>
						    <option>Gambia</option>
						    <option>Georgia</option>
						    <option>Germany</option>
						    <option>Ghana</option>
						    <option>Gibraltar</option>
						    <option>Great Britain</option>
						    <option>Greece</option>
						    <option>Greenland</option>
						    <option>Grenada</option>
						    <option>Guadeloupe</option>
						    <option>Guam</option>
						    <option>Guatemala</option>
						    <option>Guernsey</option>
						    <option>Guinea</option>
						    <option>Guinea-Bissau</option>
						    <option>Guyana</option>
						    <option>Haiti</option>
						    <option>Heard and Mc Donald Islands</option>
						    <option>Honduras</option>
						    <option>Hong Kong</option>
						    <option>Hungary</option>
						    <option>Iceland</option>
						    <option>India</option>
						    <option>Indonesia</option>
						    <option>Ireland</option>
						    <option>Israel</option>
						    <option>Italy</option>
						    <option>Jamaica</option>
						    <option>Japan</option>
						    <option>Jersey</option>
						    <option>Jordan</option>
						    <option>Kazakhstan</option>
						    <option>Kenya</option>
						    <option>Kiribati</option>
						    <option>Korea, Republic of</option>
						    <option>Kuwait</option>
						    <option>Kyrgyzstan</option>
						    <option>Lao People's Democratic Republic</option>
						    <option>Latvia</option>
						    <option>Lebanon</option>
						    <option>Lesotho</option>
						    <option>Liberia</option>
						    <option>Libya</option>
						    <option>Liechtenstein</option>
						    <option>Lithuania</option>
						    <option>Luxembourg</option>
						    <option>Macau</option>
						    <option>Macedonia</option>
						    <option>Madagascar</option>
						    <option>Malawi</option>
						    <option>Malaysia</option>
						    <option>Maldives</option>
						    <option>Mali</option>
						    <option>Malta</option>
						    <option>Marshall Islands</option>
						    <option>Martinique</option>
						    <option>Mauritania</option>
						    <option>Mauritius</option>
						    <option>Mayotte</option>
						    <option>Mexico</option>
						    <option>Micronesia, Federated States of</option>
						    <option>Moldova, Republic of</option>
						    <option>Monaco</option>
						    <option>Mongolia</option>
						    <option>Montserrat</option>
						    <option>Morocco</option>
						    <option>Mozambique</option>
						    <option>Myanmar</option>
						    <option>Namibia</option>
						    <option>Nauru</option>
						    <option>Nepal</option>
						    <option>Netherlands</option>
						    <option>Netherlands Antilles</option>
						    <option>New Caledonia</option>
						    <option>New Zealand</option>
						    <option>Nicaragua</option>
						    <option>Niger</option>
						    <option>Nigeria</option>
						    <option>Niue</option>
						    <option>Norfolk Island</option>
						    <option>Northern Ireland</option>
						    <option>Northern Mariana Islands</option>
						    <option>Norway</option>
						    <option>Oman</option>
						    <option>Pakistan</option>
						    <option>Palau</option>
						    <option>Panama</option>
						    <option>Papua New Guinea</option>
						    <option>Paraguay</option>
						    <option>Peru</option>
						    <option>Philippines</option>
						    <option>Pitcairn</option>
						    <option>Poland</option>
						    <option>Portugal</option>
						    <option>Puerto Rico</option>
						    <option>Qatar</option>
						    <option>Reunion</option>
						    <option>Romania</option>
						    <option>Russia</option>
						    <option>Russian Federation</option>
						    <option>Rwanda</option>
						    <option>Saint Kitts and Nevis</option>
						    <option>Saint Lucia</option>
						    <option>Saint Vincent and the Grenadines</option>
						    <option>Samoa (Independent)</option>
						    <option>San Marino</option>
						    <option>Sao Tome and Principe</option>
						    <option>Saudi Arabia</option>
						    <option>Scotland</option>
						    <option>Senegal</option>
						    <option>Serbia and Montenegro</option>
						    <option>Seychelles</option>
						    <option>Sierra Leone</option>
						    <option>Singapore</option>
						    <option>Slovakia</option>
						    <option>Slovenia</option>
						    <option>Solomon Islands</option>
						    <option>Somalia</option>
						    <option>South Africa</option>
						    <option>South Georgia and the South Sandwich Islands</option>
						    <option>Spain</option>
						    <option>Sri Lanka</option>
						    <option>St. Helena</option>
						    <option>St. Pierre and Miquelon</option>
						    <option>Suriname</option>
						    <option>Svalbard and Jan Mayen Islands</option>
						    <option>Swaziland</option>
						    <option>Sweden</option>
						    <option>Switzerland</option>
						    <option>Taiwan</option>
						    <option>Tajikistan</option>
						    <option>Tanzania</option>
						    <option>Thailand</option>
						    <option>Togo</option>
						    <option>Tokelau</option>
						    <option>Tonga</option>
						    <option>Trinidad</option>
						    <option>Trinidad and Tobago</option>
						    <option>Tunisia</option>
						    <option>Turkey</option>
						    <option>Turkmenistan</option>
						    <option>Turks and Caicos Islands</option>
						    <option>Tuvalu</option>
						    <option>Uganda</option>
						    <option>Ukraine</option>
						    <option>United Arab Emirates</option>
						    <option>United Kingdom</option>
						    <option>United States</option>
						    <option>United States Minor Outlying Islands</option>
						    <option>Uruguay</option>
						    <option>USA</option>
						    <option>Uzbekistan</option>
						    <option>Vanuatu</option>
						    <option>Vatican City State (Holy See)</option>
						    <option>Venezuela</option>
						    <option>Viet Nam</option>
						    <option>Virgin Islands (British)</option>
						    <option>Virgin Islands (U.S.)</option>
						    <option>Wales</option>
						    <option>Wallis and Futuna Islands</option>
						    <option>Western Sahara</option>
						    <option>Yemen</option>
						    <option>Zambia</option>
						    <option>Zimbabwe</option>
						</select>
						<p class="error_msg"></p>
					</li>
					<li><label>Address Line1<span class="font_set_orange">*</span> :</label><input type="text" name="userAddress1" id="userAddress1" /><p class="error_msg"></p></li>
					<li><p>Street address, P.O.box, company name, c/o</p></li>
					<li><label>Address Line2<span class="font_set_orange">*</span> :</label><input type="text" name="userAddress2" id="userAddress2" /><p class="error_msg"></p></li>
					<li><p>Apartment, suite, unit, building, floor, etc.</p></li>
					<li><label>City<span class="font_set_orange">*</span> :</label><input type="text" name="userCity" id="userCity" /><p class="error_msg"></p></li>
					<li><label>State, Province or Region<span class="font_set_orange">*</span> :</label><input type="text" name="userRegion" id="userRegion" /><p class="error_msg"></p></li>
					<li><label>ZIP or Postal Code<span class="font_set_orange">*</span> :</label><input type="text" name="userZipCode" id="userZipCode" /><p class="error_msg"></p></li>
					<li><label>Phone number<span class="font_set_orange">*</span> :</label><input type="text" name="userPhoneNumber" id="userPhoneNumber" /><p class="error_msg"></p></li>
				</ul>

			</div>


			<h3>Security Check</h3>
			<div class="layerBox2 register_form_box">
				<ul>
					<li><label>Image : </label> <img src="<?php echo $captcha_img?>" /></li>
					<li><label>Type the characters <br />in the above image<span class="font_set_orange">*</span> : </label><input type="text" name="captcha" id="capchaCode" /><p class="error_msg"></p></li>
				</ul>
			</div>

			<h3>[Aegis] Customer Agreement</h3>
			<div class="layerBox2 register_text_box">
				<p><input type="checkbox" name="agreement" id="agreement" /><label>Check here to indicate that you have read and agree to the terms of the [Aegis] Customer Agreement.</label></p>
				<p class="error_msg"></p>
			</div>


			<div class="btn"><a id="btnRegisterStep3Submit"><span>Step4 >></span></a></div>

            <input type=submit>
			</form>
		</div>

	</div>