<h2># step1</h2>
<label>회원가입 첫단계</label>
<p>
    - 사용자 계정 정보 입력
</p>



<form name="authFrom" method="post" target="_self" action="./step1_processing">

<ul>
    <li>email : <input type="text" name="user_email"></li>
    <li>password : <input type="password" name="user_password"></li>
    <li>repeat password : <input type="password" name="user_password"></li>
    <li><input type=submit></li>
</ul>

</form>


