	<div class="sub_container">

		<div class="content">
			<div class="register_status_bar">
				<ul>
					<li>STEP 01 >></li>
					<li>STEP 02 >></li>
					<li>STEP 03 >></li>
					<li>STEP 04 >></li>
					<li><span class="on">STEP 05</span></li>
				</ul>
			</div>
			<h3>Welcome To Aegis !</h3>
			<div class="layerBox2 register_text_box">
				<p>Your E-mail Address : <span class="font_set_blue"><?php echo $userEmail?></span></p>
				<p>
					Please remember your e-mail address for sign in [Aegis].<br />
					Your passwords are securelyencrypted and stored.<br />
					Thank you for using our services.
				</p>
			</div>
			<div class="btn"><a id="btnHome" href="/"><span>Go to a mainpage</span></a></div>

			<div class="register_page_link">
				<ul>
				<li>Do you want to learn more about [Aegis]? <a href="/html/introduction">Go to Introduction Page</a></li>
				<li>You can experience right now. <a href="/console/createInstance">Get a Demo</a></li>
				<li>Protect your web server by using [Aegis]. <a href="/console/createInstance">Register for online services</a></li>
				</ul>
			</div>
		</div>

	</div>

