	<div class="sub_container">

		<div class="content">
			<div class="register_status_bar">
				<ul>
					<li>STEP 01 >></li>
					<li><span class="on">STEP 02 >></span></li>
					<li>STEP 03 >></li>
					<li>STEP 04 >></li>
					<li>STEP 05</li>
				</ul>
			</div>
			<div class="layerBox2 register_text_box">
				<h3>Please Check Your E-mail.</h3>
				<p>You automatically received an e-mail request to verify your address [<?php echo $userEmail ?>].<br />To verify, just follow the link in the message.<br />Confirm your e-mail address and continue sign-up process.</p>
			</div>
			<!-- div class="layerBox2 register_text_box">
				<p>Do you want to resend a verification mail? <br /> <span class="font_set_orange">(Former mail is invalid if you request a mail again.)</span></p>
			</div>
			<div class="btn"><a id="btnRegisterStep2Submit"><span>Resend >></span></a></div -->
		</div>

	</div>


